config/routes.rb
Rails.application.routes.draw do
  
  resources :posts
  resources :posts
  resources :releases
  resources :artists
  resources :artist
  devise_for :users
  root 'pages#home'
  get "about" => "pages#about"
  get "releases" => "pages#releases"
  get "events" => "pages#events"
  get "events" => "pages#events"
  get "media" => "pages#media"
  get "contact" => "pages#contact"
  get "posts" => "posts#index"

devise_scope :user do
  get "/sokadmin" => "devise/sessions#new"
end

end

app/models/artist.rb
class Artist < ActiveRecord::Base
	def to_param
  	name
  end
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	validates :image, presence: true
  validates :name, presence: true
  validates :bio, presence: true
  validates :twitter, presence: true
  validates :facebook, presence: true
  validates :soundcloud, presence: true

  has_many :releases
end

app/models/post.rb
class Post < ActiveRecord::Base
has_attached_file :image, :styles => {:medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	validates :image, presence: true
  validates :title, presence: true
  validates :body, presence: true
  validates :author, presence: true
end

app/models/release.rb
class Release < ActiveRecord::Base
	belongs_to :artist
	
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	validates :image, presence: true
  validates :name, presence: true
  validates :details, presence: true
  validates :credits, presence: true
  validates :link, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    
  end

  
  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end


  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find_by_name(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :image, :bio, :twitter, :facebook, :soundcloud)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # require 'soundcloud'

  def home
  end

  def about
  end

  def releases
  end

  def artists
  end

  def events
  end

  def contact
  end

  def media
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :author, :image)
    end
end

app/controllers/releases_controller.rb
class ReleasesController < ApplicationController
  before_action :set_release, only: [:show, :edit, :update, :destroy]

  # GET /releases
  # GET /releases.json
  def index
    @releases = Release.all
  end

  # GET /releases/1
  # GET /releases/1.json
  def show
  end

  # GET /releases/new
  def new
    @release = Release.new

    @artists = Artist.all
  end

  # GET /releases/1/edit
  def edit
    @release = Release.find(params[:id])
    @artists = Artist.all
  end

  # POST /releases
  # POST /releases.json
  def create
    @release = Release.new(release_params)

    respond_to do |format|
      if @release.save
        format.html { redirect_to @release, notice: 'Release was successfully created.' }
        format.json { render :show, status: :created, location: @release }
      else
        format.html { render :new }
        format.json { render json: @release.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /releases/1
  # PATCH/PUT /releases/1.json
  def update
    respond_to do |format|
      if @release.update(release_params)
        format.html { redirect_to @release, notice: 'Release was successfully updated.' }
        format.json { render :show, status: :ok, location: @release }
      else
        format.html { render :edit }
        format.json { render json: @release.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /releases/1
  # DELETE /releases/1.json
  def destroy
    @release.destroy
    respond_to do |format|
      format.html { redirect_to releases_url, notice: 'Release was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_release
      @release = Release.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def release_params
      params.require(:release).permit(:name, :details, :link, :credits, :image, :artist_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/views/artists/_form.html.erb
<div class="container">
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

 <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control"  %>
  </div>

   <div class="form-group">
    <%= f.label :bio %><br>
    <%= f.text_area :bio, class: "form-control"  %>
  </div>

   <div class="form-group">
    <%= f.label :twitter %><br>
    <%= f.text_field :twitter, class: "form-control"  %>
  </div>

   <div class="form-group">
    <%= f.label :facebook %><br>
    <%= f.text_field :facebook, class: "form-control"  %>
  </div>

     <div class="form-group">
    <%= f.label :soundcloud %><br>
    <%= f.text_field :soundcloud, class: "form-control"  %>
  </div>


<div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>
</div>




 

app/views/artists/edit.html.erb
<div class="container">
<h1>Editing Artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>
</div>

app/views/artists/index.html.erb
<div class="container">
    <p id="notice"><%= notice %></p>

    <h3 class="center">A R T I S T S</h3>
    <hr/>
    <% if user_signed_in? %>
      <a class="btn btn-lg" <%= link_to 'Add Artist', new_artist_path %> </a>

    <% end %>
    <div class="row">

       <% @artists.each do |artist| %>
      <div class="col-md-4">
        <%= link_to image_tag(artist.image.url), artist, :class => "blur" %>
        <!-- <%= link_to image_tag(artist.image.url(:medium)), artist, :class => "blur" %> -->
        <p class="lead center">

        <%= artist.name %>
        
        <% if user_signed_in? %>
               | <%= link_to 'Edit', edit_artist_path(artist) %>
               | <%= link_to 'Delete', artist, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
        </p>
      </div>
        <% end %>
    </div>

    <br>

</div>

<br/>
<br/>
<br/>
<br/>
<br/>

app/views/artists/new.html.erb
<div class="container">
<h1>New Artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>
</div>

app/views/artists/show.html.erb
<div class="container">
	<!-- <p id="notice"><%= notice %></p> -->	
		<%= link_to '< Back', artists_path %>	
		<% if user_signed_in? %>
			| <%= link_to 'Edit', edit_artist_path(@artist) %>

			<% end %>

	<div class="row container center">
		<h3> <%= @artist.name %></h3>

	<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<hr/>
		<br/>

			</div>
	</div>

		<%= image_tag @artist.image.url,:class => "showartistimg" %>
	
		
	<div>
		<br/>
		<br/>

		<div class="row">
			<div class="col-md-6 col-md-offset-3">
			<%= @artist.bio %>
			<!-- <%= @artist.releases %> -->
		 </div> 
		</div>

		 
		<div class="row">
		<br/>
			<ul class="artistsm">
		      <li><%= link_to (image_tag 'twitter42.png',size: "25x25"), @artist.twitter, :target => "_blank" %></li>
		      <li><%= link_to (image_tag 'facebook55.png',size: "25x25"), @artist.facebook, :target => "_blank" %></li>
		      <li><%= link_to (image_tag 'soundcloud6.png',size: "25x25"), @artist.soundcloud, :target => "_blank" %></li>
	    	</ul>
	    </div>
	</div>
</div>

<div id="player1">
	
</div>


<script type="text/JavaScript">
  SC.oEmbed('<%= @artist.soundcloud %>', {color: "ff0066"},  document.getElementById("player1"));
</script>

	
<br/>
<br/>
<br/>
<br/>
<br/>
</div>

app/views/layouts/_footer.html.erb
 <div class="container">

      <div class="row">
      
        <div class="footer center">
        <ul>
      		<li><%= link_to (image_tag 'twitter3.png',size: "25x25"), "https://twitter.com/soundofkla", :target => "_blank" %></li>
      		<li><%= link_to (image_tag 'soundcloud6.png',size: "25x25"), "https://www.facebook.com/Soundofkla", :target => "_blank" %></li>
          <li><%= link_to (image_tag 'facebook55.png', size: "25x25"), "https://soundcloud.com/sokmusic", :target => "_blank" %></li>
          <li><%= link_to (image_tag 'instagram15.png', size: "25x25"), "https://instagram.com/soundofkla/", :target => "_blank" %></li>
          <li><%= link_to (image_tag 'youtube1.png', size: "25x25"), "https://www.youtube.com/user/Soundofkla", :target => "_blank" %></li>
      		<li><%= link_to (image_tag 'tumblr1.png', size: "25x25"), "http://www.soundofkla.com/", :target => "_blank" %></li>
      	</ul>
      		<p class="text-center lead">Copyright © 2015 Sound Of Kla. All rights reserved.</p>
        </div>
      </div>

 </div>

app/views/layouts/_header.html.erb
     <div class="nav">
     <nav class="navbar navbar-static-top navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header pull-left">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
 <a class="navbar-brand" href="/">S O U N D O F K L A</a>
  </div>


  <div class="collapse navbar-collapse navbar-ex1-collapse pull-right">
    <ul class="nav navbar-nav">
      <li><%= link_to "ABOUT", about_path %></li> 
      <li><%= link_to "ARTISTS", artists_path %></li>
      <li><%= link_to "RELEASES", releases_path %></li>
      <!-- <li><%= link_to "Events", events_path %></li> -->
      <li><%= link_to "+ MEDIA",  media_path %></li> 
      <li><%= link_to "CONTACT", contact_path %></li>
      
      <% if user_signed_in? %>
       <li><%= link_to "Account Settings", edit_user_registration_path %></li>
      <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li> 
      <% else %>

      <% end %>
     
    </ul>
  </div><!-- /.navbar-collapse -->

    </div>
    </nav>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sound of Kla</title>

 <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '//connect.soundcloud.com/sdk.js' %>
<%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= render 'layouts/header' %>
<% flash.each do |name, msg| %>
	<%= content_tag(:div, msg, class: "alert alert -#{name}") %>
<% end %>

<div>
<%= yield %>
<%= render 'layouts/footer' %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<div id="player"></div>


<iframe width="560" height="315" src="//www.youtube.com/user/Soundofkla" frameborder="0" allowfullscreen></iframe>

<a class="twitter-timeline" href="https://twitter.com/soundofkla" data-widget-id="610082377633804288">Tweets by @soundofkla</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>


<script type="text/JavaScript">
  SC.oEmbed("http://soundcloud.com/sokmusic", {color: "ff0066"},  document.getElementById("player"));
</script>

app/views/pages/artists.html.erb
<h1>Pages#artists</h1>
<p>Find me in app/views/pages/artists.html.erb</p>

app/views/pages/blog.html.erb
<div class="container">

 <ul class="nav navbar-nav center">
      <li><%= link_to "+ VIDEOS", releases_path %></li>
      <li><%= link_to "+ PODCASTS",  media_path %> </li> 
      <li><%= link_to "+ VISUALS", media_path %></li>
      <li><%= link_to "+ POSTS",  posts_path %></li>     
    </ul>


</div>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/events.html.erb
<h1>Pages#events</h1>
<p>Find me in app/views/pages/events.html.erb</p>

app/views/pages/home.html.erb
<div class="jumbotron">
  <div class="container text-center">       
  <h1 class="text-center">Welcome to <span class="highlight">Sound Of Kla </span> </h1>
<br/>
   <p class="lead center" style="color:#777">We are an online distribution music platform whose mission is to help you discover up and coming  <br/> artists making great music in Africa & Worldwide</p>
        <br/>
        <a class="btn btn-lg" href="about"> Discover</a>
  </div>
</div>

app/views/pages/media.html.erb
<div class="container">

 <ul class="nav navbar-nav center">
      <li><%= link_to "+ VIDEOS", media_path %></li>
      <li><%= link_to "+ PODCASTS",  media_path %> </li> 
      <li><%= link_to "+ VISUALS", media_path %></li>
      <li><%= link_to "+ POSTS",  posts_path %></li>     
    </ul>


</div>

app/views/pages/releases.html.erb
<h1>Pages#releases</h1>
<p>Find me in app/views/pages/releases.html.erb</p>

app/views/posts/_form.html.erb
<div class="container">

<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  
   <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
   <div class="form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: "form-control" %>
  </div>
   <div class="form-group">
    <%= f.label :author %><br>
    <%= f.text_field :author, class: "form-control" %>
  </div>
    <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>













 

app/views/posts/edit.html.erb
<div class="container">
<h1 class="center">Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<div class="container">

 <ul class="nav navbar-nav center">
      <li><%= link_to "+ VIDEOS", media_path %></li>
      <li><%= link_to "+ PODCASTS",  media_path %> </li> 
      <li><%= link_to "+ VISUALS", media_path %></li>
      <li><%= link_to "+ POSTS",  posts_path %></li>     
    </ul>


</div>

<div class="container">
<p id="notice"><%= notice %></p>

 <% if user_signed_in? %>
    <a class="btn btn-lg" <%= link_to 'Add Post', new_post_path %> </a>
  <% end %>

<% @posts.each do |post| %>
<div class="col-md-offset-2">
   <h1 class="center"> <%= link_to post.title, post %> </h1> 

   <div class="center">
     <%= link_to (image_tag post.image.url, size: "630x357"), post%>

   </div>

   <div class="center"><%= post.created_at %> </div>

    <div class="col-md-offset-2">
       <p><%= truncate post.body, length: 200 %>  <%= link_to 'Read more', post %></p>

         <% if user_signed_in? %>
         <div>
          <%= link_to 'Edit', edit_post_path(post) %> |
          <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
       <% end %>
    </div>
       <hr/>
 
  </div>
    <% end %>
 
<br>



</div>

app/views/posts/new.html.erb
<div class="container">
<h1 class="center">New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>

<%= link_to '< Back', posts_path %>	
		<% if user_signed_in? %>
			| <%= link_to 'Edit', edit_post_path(@post) %> 
			<% end %>

	<h3 class="center"> <%= @post.title %> </h3>

	<div class="center"><%= image_tag @post.image.url, :class =>'showpostimg' %></div>
	<br/>
	<p><%= @post.body %></p>

	<p>
	  <%= @post.created_at %> <br/>
	  written by: <strong><%= @post.author %></strong> for Soundofkla
	</p>


</div>


<br/>
<br/>
<br/>
<br/>
<br/>

app/views/releases/_form.html.erb
<div class="container">
<%= form_for(@release) do |f| %>
  <% if @release.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@release.errors.count, "error") %> prohibited this release from being saved:</h2>

      <ul>
      <% @release.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :artist_id %><br>
    <%= collection_select(:release, :artist_name, @artists, :name, :name, {:prompt =>false}) %>
  </div>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :details %><br>
    <%= f.text_area :details, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :link %><br>
    <%= f.text_field :link, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :credits %><br>
    <%= f.text_area :credits, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>
</div>






 

app/views/releases/edit.html.erb
<div class="container">
<h1>Editing Release</h1>

<%= render 'form' %>

<%= link_to 'Show', @release %> |
<%= link_to 'Back', releases_path %>
</div>

app/views/releases/index.html.erb
<div class="container">
    <p id="notice"><%= notice %></p>

    <h3 class="center">R E L E A S E S</h3>
      <hr/>

    <% if user_signed_in? %>
    <a class="btn btn-lg" <%= link_to 'Add Release', new_release_path %> </a>
  <% end %>


 <div id="releases" class="transitions-enabled">

      <% @releases.each do |release| %>

    <div class="box panel panel-default">
   
      
        <%= link_to image_tag(release.image.url(:medium)), release %>

           <div class="panel-body">

              <p class="lead center">
              
                <%= release.name %> by <%= release.artist_name %>

                 <% if user_signed_in? %>
                    | <%= link_to 'Edit', edit_release_path(release) %>
                    | <%= link_to 'Delete', release, method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>
              </p>

              <!-- <p><%= release.details %></p> -->

          </div>

    </div>

      <% end %>

  </div>
</div>
<br/>
<br/>
<br/>
<br/>
<br/>

app/views/releases/new.html.erb
<div class="container">
<h1>New Release</h1>

<%= render 'form' %>

<%= link_to 'Back', releases_path %>
</div>

app/views/releases/show.html.erb
<div class="container">
	<!-- <p id="notice"><%= notice %></p> -->

	<%= link_to '< Back', releases_path %>	
		<% if user_signed_in? %>
			| <%= link_to 'Edit', edit_release_path(@release) %> 
			<% end %>

<div class="row container center">
	 <br/>
	 
	 <h3> <%= @release.name %></h3>
	

	 <div class="row">
	 <br/>
	 <br/>
		<!-- <div class="col-md-6 col-md-offset-3">
				<hr/>
		</div> -->
		<div class="col-md-10">
			<div class="col-md-6 pull-left col-sm-3">
				 <!-- <%= image_tag @release.image.url%>  -->
				<div id="player">
	
				</div>
              <div class="center">
               <p> by <%= @release.artist_name %></p>

              <p>Share with
          		 <%= link_to (image_tag 'logotype30.png',size: "30x30"),"http://www.facebook.com/sharer.php?u=URL"+ @release.name + " from Soundofkla now on http://soundofkla.herokuapp.com"+ request.fullpath, :target => :blank %>
          		 <%= link_to (image_tag 'socialnetwork64.png',size: "30x30"),"http://twitter.com/home?status=Check out "+ @release.name + " from @soundofkla now on http://soundofkla.com"+ request.fullpath, :target => :blank %>
          		  <%= link_to (image_tag 'tumblr2.png',size: "30x30"),"https://tumblr.com/share"+ @release.name + " from @soundofkla now on http://soundofkla.com"+ request.fullpath, :target => :blank %>
				</p></div>
          
			</div>

			<div class="col-md-6 ">
					<p><%= @release.details %></p>
			  	
			  	<div class="">	
			  		<br/>
			  		<p class="lead">CREDITS </p>
			  		<%= @release.credits %>
				</div>

			</div>
		</div>
	</div>

</div>
</div>



<br/>
<br/>
<br/>
<br/>
<br/>

<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-556af2db222ada62" async="async"></script>

   
<script type="text/JavaScript">
  SC.oEmbed('<%= @release.link %>', {color: "ff0066"},  document.getElementById("player"));
</script>